name = "MetaMDPs"
uuid = "3f9a7afc-accc-48b4-be0d-fc4a8913d37e"
authors = ["Abhinav Bhatia <abhinav.bhatia.me@gmail.com>"]
version = "0.2.0"

[deps]
MDPs = "11f886ef-95cd-43ae-b218-d50c093ca059"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
